services:
  - type: web
    name: sudharshan-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    disk:
      name: portfolio-db
      mountPath: /opt/render/project/src
      sizeGB: 1
